services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-services
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=db
    restart: always

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

  db:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

